# Character in health bar of mob

heart-character: "❤"
# How many seconds should be health showed after hit

show-time: 3
# Color of active (red) heart in name

active-color: "&c"
# Changing color during time when mob health is decreasing

active-color-multiple:
  enabled: true
  one-third: "&c" #Color when health is under 1/3 and above 0/3
  two-thirds: "&e" #Color when health is under 2/3 and above 1/3
  three-thirds: "&a" #Color when health is under 3/3 and above 2/3

# Color of inactive (grey) heart in name
neutral-color: "&7"

# Show entity health bar when entity is hit by itself (for example, when skeleton starts to fire or he drops from MobTrap)
hit-by-itself: true

# Some powerful mobs could have really long health bar, you can specify a multiplier for them
mob-multipliers:
  IRON_GOLEM: 0.25 # Their real health is 75% shorter in display, because it would be too long in game
  ENDERMAN: 0.65
  POLAR_BEAR: 0.75
  WITCH: 0.75

# Whole list of mob names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
excluded-mobs:
#- WITHER_SKELETON
#- IRON_GOLEM
