main: net.minecord.beautyindicator.BeautyIndicator
name: BeautyIndicator
version: '1.7'
description: Minecraft (Spigot/Bukkit) plugin for indicating mob health
website: https://minecord.net
commands:
  beautyindicator:
    description: Help command
permissions: {}
